'use client'
import { useState } from 'react'
import { createClient } from '@supabase/supabase-js'
import { RefreshCw, Wand2 } from 'lucide-react'

type Design={projectType:string;dimensions:string;description:string;generatedDesignUrl:string;conceptName:string;customerSummary:string;designFeatures:string[];practicalNotes:string}
const refinements=['Make it more modern','Make it more luxurious','Add more security','Change colour','Make it simpler','Add pedestrian door']
const base:{[key:string]:[number,number]}={Gate:[180000,550000],Door:[90000,280000],'Burglar Proofing':[60000,200000],Railing:[70000,260000],Staircase:[220000,650000],'Custom Metal Work':[100000,400000]}
const styleMult:{[key:string]:number}={Modern:1,Classic:1,Luxury:1.35,Minimal:.9,Industrial:1};const materialMult:{[key:string]:number}={Steel:1,'Stainless steel':1.4,Aluminium:1.2,'Not sure yet':1};const USD_RATE=1550
function estimate(project:string,style:string,material:string){const [lo,hi]=base[project]||[80000,300000];const m=(styleMult[style]||1)*(materialMult[material]||1);return [Math.round(lo*m/5000)*5000,Math.round(hi*m/5000)*5000]}
function money(n:number,c:string){return c==='USD'?`$${Math.round(n/USD_RATE).toLocaleString('en-US')}`:`₦${Math.round(n).toLocaleString('en-NG')}`}
function supabase(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!u||!k)throw new Error('Supabase environment variables are missing.');return createClient(u,k)}

export default function AIStudio({onQuote}:{onQuote?:(design:Design)=>void}){
 const [form,setForm]=useState({project:'Gate',description:'',style:'Modern',material:'Steel',finish:'Black',dimensions:''});const [versions,setVersions]=useState<any[]>([]);const [active,setActive]=useState(-1);const [loading,setLoading]=useState(false);const [imageLoading,setImageLoading]=useState(false);const [error,setError]=useState('');const [imageError,setImageError]=useState('');const [currency,setCurrency]=useState('NGN')
 const current=active>=0?versions[active]:null
 async function generate(refinement?:string){setError('');setImageError('');if(!form.description.trim()&& !refinement){setError('Please describe your idea in a little more detail.');return}setLoading(true);const description=refinement?`${current.appliedDescription} — refinement: ${refinement}`:form.description;try{const sb=supabase();const {data,error:e}=await sb.functions.invoke('ai-design',{body:{description,projectType:form.project,style:form.style,material:form.material,colour:form.finish,dimensions:form.dimensions}});if(e)throw new Error(e.message);if(!data?.concept)throw new Error(data?.error||'Unable to create the concept.');let image='';setImageLoading(true);try{const r=await sb.functions.invoke('ai-design-image',{body:{description,projectType:form.project,style:form.style,material:form.material,colour:form.finish,dimensions:form.dimensions,conceptName:data.concept.concept_name,designFeatures:data.concept.design_features}});if(r.error)throw new Error(r.error.message);image=r.data?.image||''}catch(e){setImageError(e instanceof Error?e.message:'Unable to generate the visual design.')}finally{setImageLoading(false)}const version={concept:data.concept,image,appliedDescription:description};setVersions(v=>[...v,version]);setActive(versions.length)}catch(e){setError(e instanceof Error?e.message:'Unable to create the concept.')}finally{setLoading(false)}}
 async function saveImage(image:string){if(!image)return '';if(image.startsWith('http'))return image;try{const sb=supabase();const b=image.split(',')[1];if(!b)throw new Error('Invalid generated image.');const raw=atob(b),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);const path=`generated/${crypto.randomUUID()}.png`;const {error:e}=await sb.storage.from('ai-designs').upload(path,bytes,{contentType:'image/png',cacheControl:'31536000'});if(e)throw e;return sb.storage.from('ai-designs').getPublicUrl(path).data.publicUrl}catch(e){setImageError(e instanceof Error?e.message:'Unable to save the design image.');return ''}}
 async function quote(){const url=await saveImage(current?.image||'');onQuote?.({projectType:form.project,dimensions:form.dimensions,description:current.appliedDescription,generatedDesignUrl:url,conceptName:current.concept.concept_name,customerSummary:current.concept.customer_summary,designFeatures:current.concept.design_features||[],practicalNotes:current.concept.practical_notes||''})}
 const [low,high]=estimate(form.project,form.style,form.material)
 return <div className="ai-studio-live"><div className="ai-form"><label>What do you want to build?<select value={form.project} onChange={e=>setForm({...form,project:e.target.value})}>{['Gate','Door','Burglar Proofing','Railing','Staircase','Custom Metal Work'].map(x=><option key={x}>{x}</option>)}</select></label><label>Describe your idea<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={5} placeholder="Example: A large black double gate with clean horizontal lines, a pedestrian door and a premium finish."/></label><div className="ai-options"><label>Style<select value={form.style} onChange={e=>setForm({...form,style:e.target.value})}>{['Modern','Classic','Luxury','Minimal','Industrial'].map(x=><option key={x}>{x}</option>)}</select></label><label>Material<select value={form.material} onChange={e=>setForm({...form,material:e.target.value})}>{['Steel','Stainless steel','Aluminium','Not sure yet'].map(x=><option key={x}>{x}</option>)}</select></label><label>Finish<select value={form.finish} onChange={e=>setForm({...form,finish:e.target.value})}>{['Black','White','Grey','Metallic','Not sure yet'].map(x=><option key={x}>{x}</option>)}</select></label></div><input value={form.dimensions} onChange={e=>setForm({...form,dimensions:e.target.value})} placeholder="Approximate dimensions (optional)"/><button className="button primary" onClick={()=>generate()} disabled={loading}><Wand2 size={16}/>{loading?'Creating your concept…':'Design My Project ↗'}</button>{error&&<p className="formstatus">{error}</p>}</div>
 <div className="ai-result">{current?<><div className="sectiontag">AI CONCEPT {versions.length>1?`· v${active+1}`:''}</div>{imageLoading?<div className="ai-image-loading"><span>✦</span><p>Creating your visual design…</p></div>:current.image?<div className="ai-image-wrap"><a href={current.image} target="_blank" rel="noreferrer"><img src={current.image} alt={current.concept.concept_name}/></a><div className="ai-image-label">AI VISUAL CONCEPT · FOR DESIGN DIRECTION</div></div>:<div className="ai-image-error">{imageError||'Visual concept unavailable.'}</div>}<h3>{current.concept.concept_name}</h3><p>{current.concept.customer_summary}</p><h4>Design features</h4><ul>{(current.concept.design_features||[]).map((x:string,i:number)=><li key={i}>{x}</li>)}</ul><h4>Practical notes</h4><p>{current.concept.practical_notes}</p><div className="ai-estimate"><span>Estimated range<br/><b>{money(low,currency)} – {money(high,currency)}</b><small>Rough guide only — final price confirmed after inspection.</small></span><div><button onClick={()=>setCurrency('NGN')}>NGN</button><button onClick={()=>setCurrency('USD')}>USD</button></div></div>{versions.length>1&&<div className="ai-versions">{versions.map((_,i)=><button key={i} onClick={()=>setActive(i)} className={i===active?'active':''}>v{i+1}</button>)}</div>}<div className="ai-refinements"><b>Refine this design</b>{refinements.map(r=><button key={r} disabled={loading} onClick={()=>generate(r)}><RefreshCw size={12}/>{r}</button>)}</div><button className="button light" onClick={quote}>Send a Quote for This Design ↗</button><button className="ai-reset" onClick={()=>{setVersions([]);setActive(-1);setForm({...form,description:''})}}>Start over with a new idea</button></>:<div className="ai-empty"><span>✦</span><h3>Your concept will appear here</h3><p>Describe what you imagine. Generate, refine and send the selected design for a quote.</p></div>}</div></div>
}
