'use client'

import { useEffect, useState } from 'react'

const STATUSES = ['Draft','Sent','Accepted','Rejected','In Production','Completed']
const ink = '#1E2023', paper = '#EDEEE9', raised = '#F6F6F2', line = '#C7C4BA', steel = '#35505E', rust = '#A64B2A', green = '#4C6B4F'

type Quote = { id:string; quote_number:string; customer_name:string; phone:string; location?:string; project_type?:string; description?:string; items:any[]; subtotal:number; discount:number; deposit_pct:number; deposit_amount:number; total:number; validity_days:number; status:string; design_image_url?:string; created_at:string }

function money(n:number) { return `₦${Number(n || 0).toLocaleString('en-NG', { maximumFractionDigits:0 })}` }

export default function Dashboard() {
  const [loggedIn, setLoggedIn] = useState(false), [password, setPassword] = useState(''), [quotes, setQuotes] = useState<Quote[]>([]), [search, setSearch] = useState(''), [loading, setLoading] = useState(false), [error, setError] = useState('')
  const [form, setForm] = useState({ customer:'',phone:'',location:'',project:'Gate',description:'',discount:'0',depositPct:'50',validityDays:'14',items:[{desc:'',qty:'1',unitPrice:'0'}] })

  async function load() { setLoading(true); const res = await fetch(`/api/quotations?search=${encodeURIComponent(search)}`); if (res.status === 401) { setLoggedIn(false); setLoading(false); return } const data = await res.json(); if (!res.ok) setError(data.error || 'Unable to load quotations.'); else setQuotes(data.quotations || []); setLoading(false) }
  useEffect(() => { if (loggedIn) load() }, [loggedIn, search])
  async function login(e:React.FormEvent) { e.preventDefault(); setError(''); const res = await fetch('/api/admin-auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})}); if(!res.ok){setError((await res.json()).error||'Invalid password.');return} setPassword(''); setLoggedIn(true) }
  async function logout(){await fetch('/api/admin-auth',{method:'DELETE'});setLoggedIn(false)}
  async function createQuote(e:React.FormEvent){e.preventDefault();setError('');const res=await fetch('/api/quotations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,discount:Number(form.discount),depositPct:Number(form.depositPct),validityDays:Number(form.validityDays)})});const data=await res.json();if(!res.ok){setError(data.error||'Could not create quote.');return}setForm({...form,customer:'',phone:'',location:'',description:'',items:[{desc:'',qty:'1',unitPrice:'0'}]});load()}
  async function status(id:string,status:string){const res=await fetch(`/api/quotations/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});if(!res.ok)setError('Could not update status.');else load()}
  if(!loggedIn) return <main style={{minHeight:'100vh',background:paper,fontFamily:'Arial,sans-serif',display:'grid',placeItems:'center',padding:24}}><form onSubmit={login} style={{width:'100%',maxWidth:380,background:raised,border:`1px solid ${line}`,padding:24}}><h1 style={{color:ink}}>Stephen Metal Works</h1><p style={{color:ink,opacity:.65}}>Staff quotation dashboard</p><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Admin password" style={{width:'100%',padding:12,margin:'14px 0',border:`1px solid ${line}`,background:paper}} required/><button style={{width:'100%',padding:12,background:rust,color:'#fff',border:0,fontWeight:700}}>Sign in</button>{error&&<p style={{color:rust}}>{error}</p>}</form></main>
  return <main style={{minHeight:'100vh',background:paper,fontFamily:'Arial,sans-serif',padding:20,color:ink}}><div style={{maxWidth:1200,margin:'0 auto'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:20}}><div><h1 style={{margin:0}}>Quotation Dashboard</h1><p style={{margin:'6px 0',opacity:.6}}>Create, track and download customer quotations.</p></div><button onClick={logout} style={{padding:'9px 14px',border:`1px solid ${line}`,background:raised}}>Sign out</button></header>
  <section style={{background:raised,border:`1px solid ${line}`,padding:16,marginBottom:20}}><h2 style={{marginTop:0}}>Create quotation</h2><form onSubmit={createQuote} style={{display:'grid',gap:10}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}>{[['customer','Customer name'],['phone','Phone'],['location','Location']].map(([k,p])=><input key={k} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={p} required={k!=='location'} style={{padding:10,border:`1px solid ${line}`,background:paper}}/>)}<select value={form.project} onChange={e=>setForm({...form,project:e.target.value})} style={{padding:10,border:`1px solid ${line}`,background:paper}}>{['Gate','Door','Burglar Proofing','Railing','Staircase','Custom Metal Work'].map(x=><option key={x}>{x}</option>)}</select></div><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description / scope" rows={3} style={{padding:10,border:`1px solid ${line}`,background:paper}}/>
  {form.items.map((it,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'1fr 90px 140px 40px',gap:8}}><input value={it.desc} onChange={e=>{const items=[...form.items];items[i]={...items[i],desc:e.target.value};setForm({...form,items})}} placeholder="Item" style={{padding:9,border:`1px solid ${line}`,background:paper}}/><input type="number" min="0" value={it.qty} onChange={e=>{const items=[...form.items];items[i]={...items[i],qty:e.target.value};setForm({...form,items})}} style={{padding:9,border:`1px solid ${line}`,background:paper}}/><input type="number" min="0" value={it.unitPrice} onChange={e=>{const items=[...form.items];items[i]={...items[i],unitPrice:e.target.value};setForm({...form,items})}} placeholder="Unit price" style={{padding:9,border:`1px solid ${line}`,background:paper}}/><button type="button" onClick={()=>setForm({...form,items:form.items.filter((_,j)=>j!==i)})}>×</button></div>)}<button type="button" onClick={()=>setForm({...form,items:[...form.items,{desc:'',qty:'1',unitPrice:'0'}]})} style={{justifySelf:'start',padding:'7px 10px'}}>+ Add item</button><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10}}><input type="number" min="0" value={form.discount} onChange={e=>setForm({...form,discount:e.target.value})} placeholder="Discount" style={{padding:10,border:`1px solid ${line}`,background:paper}}/><input type="number" min="0" max="100" value={form.depositPct} onChange={e=>setForm({...form,depositPct:e.target.value})} placeholder="Deposit %" style={{padding:10,border:`1px solid ${line}`,background:paper}}/><input type="number" min="1" value={form.validityDays} onChange={e=>setForm({...form,validityDays:e.target.value})} placeholder="Validity days" style={{padding:10,border:`1px solid ${line}`,background:paper}}/></div><button style={{padding:12,background:green,color:'#fff',border:0,fontWeight:700}}>Create quotation</button></form></section>
  <section style={{background:raised,border:`1px solid ${line}`,padding:16}}><div style={{display:'flex',gap:10,marginBottom:14}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer, quote number or project" style={{flex:1,padding:10,border:`1px solid ${line}`,background:paper}}/><button onClick={load}>Refresh</button></div>{error&&<p style={{color:rust}}>{error}</p>}{loading?<p>Loading…</p>:quotes.map(q=><article key={q.id} style={{borderTop:`1px solid ${line}`,padding:'14px 0',display:'grid',gap:8}}><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><b style={{color:steel}}>{q.quote_number}</b><div style={{fontSize:18,fontWeight:700}}>{q.customer_name}</div><div style={{opacity:.65}}>{q.project_type} · {money(q.total)}</div></div><select value={q.status} onChange={e=>status(q.id,e.target.value)} style={{padding:8,border:`1px solid ${line}`,background:paper}}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><a href={`/api/quotations/${q.id}/pdf`} target="_blank" rel="noreferrer" style={{padding:'7px 10px',background:steel,color:'#fff',textDecoration:'none'}}>PDF</a>{q.design_image_url&&<a href={q.design_image_url} target="_blank" rel="noreferrer" style={{padding:'7px 10px',border:`1px solid ${line}`}}>Design image</a>}</div></article>)}{!quotes.length&&!loading&&<p style={{opacity:.6}}>No quotations yet.</p>}</section></div></main>
}
